### PR TITLE
Add a field for the version of the standard the data is published to

### LINKED ISSUE #91: Add a field for the version of the standard the data is published to
Related discussion about how to model this in OCDS: https://github.com/open-contracting/standard/issues/426

### PR DESCRIPTION
**Pull request by duncandewhurst**
**Related issues**
*Add links to related issues here. Use [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) if you want an issue to be automatically closed when the PR is merged.*
* Closes #91

**Description**
*If the changes in the PR are not sufficiently explained by the related issues and commit messages, add a description here*

Also updates `examples/csv/nodes.csv` to reflect the change in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/commit/2e6d36c79bb44c0a90867aa04ef4843d1d97003c

**Merge checklist**
- [x] If there are changes to `network-schema.json`, `network-package-schema.json`, `reference/publication_formats/json.md`, `reference/publication_formats/geojson.md` or `guidance/publication.md#how-to-publish-large-networks`, update the relevant manually authored examples:
  - [ ] `examples/json/`:
    - [ ] `network-package.json`
    - [ ] `api-response.json`
    - [ ] `multiple-networks.json`
    - [ ] `network-embedded.json`
    - [ ] `network-separate-endpoints.json`
    - [ ] `network-separate-files.json`
    - [ ] `nodes-endpoint.json`
    - [ ] `spans-endpoint.json`
  - [ ] `examples/geojson/`:
    - [ ] `api-response.geojson`
    - [ ] `multiple-networks.geojson`
- [x] Run `./manage.py pre-commit` to update derivative schema files, reference documentation and examples
- [x] If there are changes to `examples/geojson/nodes.geojson` or `examples/geojson/spans.geojson`, check and update the data use examples:
  - [ ] `examples/leaflet/leaflet.ipynb`
  - [ ] `examples/qgis/geojson.qgs`
- [x] Update the changelog ([style guide](https://ofds-standard-development-handbook.readthedocs.io/en/latest/style/changelog_style_guide.html))

---

@odscjames assigning to you for a review as I think this might be helpful to get merged before @lgs85 returns from leave.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by duncandewhurst** [comment]
Noting that this PR may need updating based on https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/13#issuecomment-1291072108

**Comment by duncandewhurst** [comment]
@odscjames I've made the update discussed in https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/13. Prior to draft 2020-12, [tuple validation was handled differently](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation) so this schema will only behave as intended with validators that support draft 2020-12. jsonschema [supports 2020-12](https://github.com/python-jsonschema/jsonschema#features) so hopefully that is not an issue for CoVE.

In order to permit only one 'describedby' link in `links`, I've added a `pattern` validation to `Link.rel` to permit any value except 'describedby'. However, I've run into the same issue as described in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/145, whereby the regex does not behave as expected when I test it with https://www.jsonschemavalidator.net/. Any ideas?

**Comment by duncandewhurst** [comment]
@odscjames I've fixed the regex issue (thanks to @lgs85) so this is ready for you to review again. In particular, please check that you're happy with the use of JSON Schema 2020-12 described in my previous comment. Thanks!

**Review by ghost — DISMISSED** [review]

**Comment by duncandewhurst** [comment]
I had to resolve a merge conflict in the changelog so another review is required.

**Review by ghost — APPROVED** [review]

**Pull request merged**
