### PR TITLE
Replace id with $id and definitions with $defs in schema files

### LINKED ISSUE #206: Use relative links to jsonschema anchors
See https://github.com/OpenDataServices/sphinxcontrib-opendataservices/issues/43#issuecomment-1334305805

### LINKED ISSUE #212: Change `id` to `$id` in schema
In the JSON schema files, the URI is specified with the `id` keyword. However, `id` was replaced with `$id` in [draft-06](https://json-schema.org/draft-06/json-schema-release-notes.html).

### LINKED ISSUE #214: Change `definitions` to `$defs` in schema
The `definitions` keyword was changed to `$defs` in the [2019-09 release](https://json-schema.org/draft/2019-09/release-notes.html#keyword-changes). We should update our schema files to reflect this.

### LINKED ISSUE #216: Carry out a comprehensive check of schema against 2020-12 specification
Following #214 and #212 we should check for similar issues in a structured way

### PR DESCRIPTION
**Pull request by duncandewhurst**
**Related issues**

* Closes #212
* Closes #214 
* Closes #216
* Closes #206

**Description**

In addition to replacing `id` and `definitions`, I checked for other issues by running the schema through [alterschema](https://github.com/sourcemeta/alterschema) and manually reviewing the releases notes for JSON schema drafts 06, 07, 2019-09 and 2020-12.

Alongside the updates to the schema, this PR makes the associated changes to `.manage.py` and documentation markdown files.

- [x] Before merging, we should check that CoVE and Flatten Tool behave as expected with the revised schema.

**Merge checklist**

- [x] Update the changelog ([style guide](https://ofds-standard-development-handbook.readthedocs.io/en/latest/style/changelog_style_guide.html))
- [x] Run `./manage.py pre-commit` to update derivative schema files, reference documentation and examples

If there are changes to `network-schema.json`, `network-package-schema.json`, `reference/publication_formats/json.md`, `reference/publication_formats/geojson.md` or `guidance/publication.md#how-to-publish-large-networks`, update the relevant manually authored examples:

- [ ] `examples/json/`:
  - [ ] `network-package.json`
  - [ ] `api-response.json`
  - [ ] `multiple-networks.json`
  - [ ] `network-embedded.json`
  - [ ] `network-separate-endpoints.json`
  - [ ] `network-separate-files.json`
  - [ ] `nodes-endpoint.json`
  - [ ] `spans-endpoint.json`
- [ ] `examples/geojson/`:
  - [ ] `api-response.geojson`
  - [ ] `multiple-networks.geojson`

If you used a validation keyword, type or format that is not [already used in the schema](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage):

- [ ] Update the list of validation keywords, types or formats in [JSON Schema usage](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage).
- [ ] Add a field that fails validation against the new keyword, type or format to [`network-package-invalid.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-invalid.json).
- [ ] Check that [OFDS CoVE](https://ofds.cove.opendataservices.coop/) reports an appropriate validation error.

If you added a normative rule that is not encoded in JSON Schema:

- [ ] Update the list of [other normative rules](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#other-normative-rules).
- [ ] Add a field that does not conform to the rule to [`network-package-additional-checks.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-additional-checks.json).
- [ ] Open a [new issue](https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/new/choose) to add an additional check to Lib Cove OFDS.

If there are changes to `examples/geojson/nodes.geojson` or `examples/geojson/spans.geojson`, check and update the data use examples:

- [ ] `examples/leaflet/leaflet.ipynb`
- [ ] `examples/qgis/geojson.qgs`

### CODE REVIEW

**Comment by duncandewhurst** [comment]
> Before merging, we should check that CoVE and Flatten Tool behave as expected with the revised schema.

@odscjames please could you set up a test instance of CoVE using the schema in this PR?

**Comment by ghost** [comment]
> @odscjames please could you set up a test instance of CoVE using the schema in this PR?

As discussed this morning, I've just put it through tests. 

Commit https://github.com/Open-Telecoms-Data/lib-cove-ofds/commit/eb855a0172a4d32458738dde87137381180138c0 changes to this schema, test run fails at: https://github.com/Open-Telecoms-Data/lib-cove-ofds/actions/runs/4808076148

Haven't had time to work out why yet.

(You can see in https://github.com/Open-Telecoms-Data/lib-cove-ofds/tree/main/tests/fixtures/jsonschemavalidate the test data used.)

**Comment by duncandewhurst** [comment]
Thanks! The [test output](https://github.com/Open-Telecoms-Data/lib-cove-ofds/actions/runs/4808076148/jobs/8557605898#step:6:156) suggests it's trying to resolve a new pointer (`$defs/Node`) against the old schema:

```
 self = <jsonschema.validators.RefResolver object at 0x7f8632c2d870>
document = {'$schema': 'https://json-schema.org/draft/2020-12/schema', 'definitions': {'Address': {'description': 'An address.', ...https://raw.githubusercontent.com/Open-Telecoms-Data/open-fibre-data-standard/0__2__0/schema/network-schema.json', ...}
fragment = '$defs/Node'
```

**Comment by ghost** [comment]
It's the ID being wrong in the schema. I made a new branch in this repo that fixed the $id in the schema files. Then I changed my test branch in libcoveofds to use that and tests work fine: https://github.com/Open-Telecoms-Data/lib-cove-ofds/actions/runs/4817157728

So using $def & $id, it turns out it's important to make sure the $id is correct. We should maybe look into whether we can tweak that in our tooling. I'm expect there will be something we can do, probably with custom RefResolver's when using jsonschema library.

But this suggests once $id's work out the json schema validate bit of libcoveofds will work fine.

**Comment by duncandewhurst** [comment]
Great! Currently, we do not update the `$id` until [preparing for a new release](https://ofds-standard-development-handbook.readthedocs.io/en/latest/technical/deploy.html#prepare-for-release). Do you think we should be updating it in each PR? If so, I'm struggling to see what to change it to that won't then be 'wrong' once the PR is merged.

**Comment by ghost** [comment]
> Do you think we should be updating it in each PR? If so, I'm struggling to see what to change it to that won't then be 'wrong' once the PR is merged.

Yeah, that could be a pain. Let me look into how the JSONSchema lib is doing the refs/loading and see if I can change something there.

**Comment by duncandewhurst** [comment]
Sounds like we'll have a solution for LibCoveOFDS one way or another.

There were no changes to the CSV examples or template after running pre-commit, which includes Flatten Tool, so I think this PR is ready for review.

**Comment by ghost** [comment]
Think we have a solution; currently libcoveofds is downloading the schema on each use and doing some dodgy de-reffing. If we switch libcoveofds to bundle the complied schema ready for use, we avoid all these problems. This is the approach we use in BODS and it's slightly faster and not reliant on github being up too.

Here's the test run with the schema from this PR, and it works fine, no $id hacking required: https://github.com/Open-Telecoms-Data/lib-cove-ofds/actions/runs/4884576924

**Comment by duncandewhurst** [comment]
Great! Thanks @odscjames :-)

**Review by rhiaro — APPROVED** [review]

**Pull request merged**
